version: 2.1
orbs:
  continuation: cci-labs/s3-cache@dev:alpha
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  # Basic command test with simple cache key
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # - run:
      #     name: Create test cache directory
      #     command: |
      #       mkdir -p test-cache
      #       echo "test data" > test-cache/data.txt
      # - continuation/save-cache:
      #     bucket-name: cci-labs-bucket
      #     cache-key: '${CIRCLE_PROJECT_REPONAME}-v1-{{ checksum "package-lock.json" }}'
      #     cache-path: "test-cache"

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: cci-labs/s3-cache
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# VS Code Extension Version: 1.4.0